export default {
    RECEIVE_ARTICLE_LIST: 'RECEIVE_ARTICLE_LIST',
    RECEIVE_ARTICLE_ITEM: 'RECEIVE_ARTICLE_ITEM',
    RECEIVE_USER_LIST: 'RECEIVE_USER_LIST',
    RECEIVE_CATEGORY_LIST: 'RECEIVE_CATEGORY_LIST',
    CHANGE_CATEGORY_LOCAL: 'CHANGE_CATEGORY_LOCAL',
    RECEIVE_TAG_LIST: 'RECEIVE_TAG_LIST',
    CHANGE_TAG_LOCAL: 'CHANGE_TAG_LOCAL',
    RECEIVE_RESOURCE_LIST: 'RECEIVE_RESOURCE_LIST',
    CHANGE_RESOURCE_LOCAL: 'CHANGE_RESOURCE_LOCAL',
    CHANGE_RESOURCE_ITEM_LOCAL: 'CHANGE_RESOURCE_ITEM_LOCAL',
    SET_LIKE_STATUS: 'SET_LIKE_STATUS',
    SET_HIGHLIGHT_INDEX: 'SET_HIGHLIGHT_INDEX',
    SET_CARD_CATEGORY_INDEX: 'SET_CARD_CATEGORY_INDEX',
    SET_SIGN_IN_MODAL: 'SET_SIGN_IN_MODAL',
    SET_SIGN_UP_MODAL: 'SET_SIGN_UP_MODAL',
    SAVE_SCROLL_TOP: 'SAVE_SCROLL_TOP'
};
