export default {
    RECEIVE_ARTICLE_LIST: 'RECEIVE_ARTICLE_LIST',
    RECEIVE_ARTICLE_ITEM: 'RECEIVE_ARTICLE_ITEM',
    SET_LIKE_STATUS: 'SET_LIKE_STATUS',
    SET_HIGHLIGHT_INDEX: 'SET_HIGHLIGHT_INDEX',
    SET_CARD_CATEGORY_INDEX: 'SET_CARD_CATEGORY_INDEX',
    SET_SIGN_IN_MODAL: 'SET_SIGN_IN_MODAL',
    SET_SIGN_UP_MODAL: 'SET_SIGN_UP_MODAL',
    SAVE_SCROLL_TOP: 'SAVE_SCROLL_TOP'
};
